# Generated by Django 4.2.6 on 2023-11-13 08:14

from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_vacancy_min_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateField(null=True, validators=[vacancies.models.check_date_not_past]),
        ),
    ]
